const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.iframe,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.iframe.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{bg0: 0},
	{buttonOption0: 0},
	{buttonOption1: 0},
	{buttonOption2: 0},
	{Mouse: 0},
	{avatar0: 0},
	{avatar1: 0},
	{avatar2: 0},
	{Fade: 0},
	{SpriteStart: 0},
	{cena2_: 0},
	{cena2_2: 0},
	{cena2_3: 0},
	{TextoStartCutscene: 0},
	{SpriteStartCutscene: 0},
	{TinderFundo: 0},
	{TextoTinder: 0},
	{Tinder0: 0},
	{Tinder1: 0},
	{Tinder2: 0},
	{TinderFt0: 0},
	{TinderFt1: 0},
	{TinderFt2: 0},
	{SpriteTinder: 0},
	{iframe: 0},
	{TextoCorrida: 0},
	{SpriteCorrida: 0},
	{surfista: 0},
	{goodvibes: 0},
	{gabriel: 0},
	{TextoGabriel: 0},
	{TextoGoodvibes: 0},
	{TextoSurfista: 0},
	{gabriel_0: 0},
	{TextoNamoro: 0},
	{gabriel_: 0},
	{gabriel_2: 0},
	{surfista2: 0},
	{TextoSurfista2: 0},
	{Goodvibes2: 0},
	{TextoGoodvibes2: 0},
	{SpriteProposalNo: 0},
	{SpriteProposalYes: 0},
	{gabriel2: 0},
	{gabriel3: 0},
	{avatarChoice: 0},
	{matchOk: 0},
	{coinBalance: 0},
	{transportChoice: 0},
	{finished: 0},
	{TinderChosen: 0},
	{TinderChoice: 0},
	{GameDone: 0},
	{TravelRead: 0},
	{ProposalEnded: 0}
];

self.InstanceType = {
	bg0: class extends self.ISpriteInstance {},
	buttonOption0: class extends self.ISpriteInstance {},
	buttonOption1: class extends self.ISpriteInstance {},
	buttonOption2: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	avatar0: class extends self.ISpriteInstance {},
	avatar1: class extends self.ISpriteInstance {},
	avatar2: class extends self.ISpriteInstance {},
	SpriteStart: class extends self.ISpriteInstance {},
	cena2_: class extends self.ISpriteInstance {},
	cena2_2: class extends self.ISpriteInstance {},
	cena2_3: class extends self.ISpriteInstance {},
	TextoStartCutscene: class extends self.ITextInstance {},
	SpriteStartCutscene: class extends self.ISpriteInstance {},
	TinderFundo: class extends self.ISpriteInstance {},
	TextoTinder: class extends self.ITextInstance {},
	Tinder0: class extends self.ISpriteInstance {},
	Tinder1: class extends self.ISpriteInstance {},
	Tinder2: class extends self.ISpriteInstance {},
	TinderFt0: class extends self.ISpriteInstance {},
	TinderFt1: class extends self.ISpriteInstance {},
	TinderFt2: class extends self.ISpriteInstance {},
	SpriteTinder: class extends self.ISpriteInstance {},
	iframe: class extends self.IIframeInstance {},
	TextoCorrida: class extends self.ITextInstance {},
	SpriteCorrida: class extends self.ISpriteInstance {},
	surfista: class extends self.ISpriteInstance {},
	goodvibes: class extends self.ISpriteInstance {},
	gabriel: class extends self.ISpriteInstance {},
	TextoGabriel: class extends self.ITextInstance {},
	TextoGoodvibes: class extends self.ITextInstance {},
	TextoSurfista: class extends self.ITextInstance {},
	gabriel_0: class extends self.ISpriteInstance {},
	TextoNamoro: class extends self.ITextInstance {},
	gabriel_: class extends self.ISpriteInstance {},
	gabriel_2: class extends self.ISpriteInstance {},
	surfista2: class extends self.ISpriteInstance {},
	TextoSurfista2: class extends self.ITextInstance {},
	Goodvibes2: class extends self.ISpriteInstance {},
	TextoGoodvibes2: class extends self.ITextInstance {},
	SpriteProposalNo: class extends self.ISpriteInstance {},
	SpriteProposalYes: class extends self.ISpriteInstance {},
	gabriel2: class extends self.ISpriteInstance {},
	gabriel3: class extends self.ISpriteInstance {}
}